language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

notifications:
  email: false

sudo: false

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v